/*TEAM*/

CREATE TABLE TEAM(

TEAM_NAME VARCHAR(30) NOT NULL,

TEAM_CITY VARCHAR(20) NOT NULL,

TEAM_MASCOT VARCHAR(15),

TEAM_HOME_COLOR VARCHAR(10),

TEAM_AWAY_COLOR VARCHAR(10),

TEAM_HOME_NUM_COLOR VARCHAR (10),

TEAM_AWAY_NUM_COLOR VARCHAR (10),

CONSTRAINT TEAM_PK_TEAM_NAME

PRIMARY KEY(TEAM_NAME),

UNIQUE(TEAM_NAME));

/*TEAM_STATISTICS*/

CREATE TABLE TEAM_STATISTICS(

TEAM_NAME VARCHAR(30) NOT NULL,

TS_WINS SMALLINT DEFAULT 0,

TS_LOSS SMALLINT DEFAULT 0,

TS_FOULS SMALLINT DEFAULT 0,

TS_TOTAL_POINTS INT DEFAULT 0,

TS_TOTAL_TIMEOUTS SMALLINT DEFAULT 0,

CONSTRAINT TEAM_STATISTICS_PK_TEAM_NAME

PRIMARY KEY(TEAM_NAME),

CONSTRAINT TEAM_STATISTICS_TEAM_NAME_FK

FOREIGN KEY (TEAM_NAME)

REFERENCES TEAM(TEAM_NAME),

UNIQUE(TEAM_NAME));

/*COACH*/

CREATE TABLE COACH(

COACH_ID MEDIUMINT NOT NULL,

TEAM_NAME VARCHAR(30) NOT NULL,

COACH_DOB DATE NOT NULL,

COACH_FNAME VARCHAR(15) NOT NULL,

COACH_LNAME VARCHAR(15) NOT NULL,

COACH_ROLE VARCHAR(30) NOT NULL CHECK(COACH_ROLE IN ('Offensive Coach', 'Defensive Coach', 'Physical Training Coach')),

COACH_HIRE_DATE DATE NOT NULL,

CONSTRAINT COACH_PK_COACH_ID

PRIMARY KEY(COACH_ID),

CONSTRAINT COACH_TEAM_NAME_FK

FOREIGN KEY (TEAM_NAME)

REFERENCES TEAM(TEAM_NAME),

UNIQUE(COACH_ID));

/*SCHEDULE*/

CREATE TABLE SCHEDULE(

GAME_ID MEDIUMINT NOT NULL,

TEAM_NAME VARCHAR(30) NOT NULL,

S_GAME_NUMBER_OF_WEEK SMALLINT NOT NULL,

S_WEEK_NUMBER SMALLINT NOT NULL,

S_HOME VARCHAR(3) NOT NULL,

S_AWAY VARCHAR(3) NOT NULL,

CHECK(S_HOME = 'YES' OR S_HOME = 'NO'),

CHECK(S_AWAY = 'YES' OR S_AWAY = 'NO'),

CONSTRAINT SCHEDULE_PK_GAME_ID_TEAM_NAME

PRIMARY KEY(GAME_ID, TEAM_NAME),

CONSTRAINT SCHEDULE_TEAM_NAME_FK

FOREIGN KEY (TEAM_NAME)

REFERENCES TEAM(TEAM_NAME),

UNIQUE(GAME_ID, TEAM_NAME));

/*PLAYER*/

CREATE TABLE PLAYER(

PLAYER_ID MEDIUMINT NOT NULL,

TEAM_NAME VARCHAR(30) NOT NULL,

PLAYER_JNUMBER SMALLINT NOT NULL,

PLAYER_FNAME VARCHAR(15),

PLAYER_LNAME VARCHAR(15),

PLAYER_DOB DATE CHECK(PLAYER_DOB > '1900-01-01'),

PLAYER_CONTRACT_LENGTH SMALLINT NOT NULL,

CONSTRAINT PLAYER_PK_PLAYER_ID

PRIMARY KEY(PLAYER_ID),

CONSTRAINT PLAYER_TEAM_NAME_FK

FOREIGN KEY (TEAM_NAME)

REFERENCES TEAM(TEAM_NAME),

UNIQUE(PLAYER_ID));

/*PLAYER_STATISTICS*/

CREATE TABLE PLAYER_STATISTICS(

PLAYER_ID MEDIUMINT NOT NULL,

PS_FREE_THROW_MISSED SMALLINT DEFAULT 0,

PS_FREE_THROW_MADE SMALLINT DEFAULT 0,

PS_TURNOVERS SMALLINT DEFAULT 0,

PS_POINTS SMALLINT DEFAULT 0,

PS_FOULS SMALLINT DEFAULT 0,

CONSTRAINT PLAYER_STATISTICS_PK_PLAYER_ID

PRIMARY KEY(PLAYER_ID),

CONSTRAINT PLAYER_STATISTICS_PLAYER_ID_FK

FOREIGN KEY (PLAYER_ID)

REFERENCES PLAYER(PLAYER_ID),

UNIQUE(PLAYER_ID));
